### ISSUE TITLE
Outdated press list subscribe email

### ISSUE THREAD

**Issue by pedropaulosuzuki** [elementary/press-kit#5]
### What Happened?

When you subscribe to the elementary press list, you receive a welcome email. This email is, however, outdated. It deadnames Danielle and still includes Cassidy, as we can see below:

![image](https://github.com/user-attachments/assets/7b0872f4-d5e4-4b0e-8def-9142e5dc50c4)

### Steps to Reproduce

1. Subscribe to the elementary press list
1. Open the email

### Expected Behavior

See "Danielle Foré, Founder & CEO" as signature, not "Daniel Foré + Cassidy"

**Comment by danirabbit** [comment]
Oops, thanks for reporting that!

**Comment by danirabbit** [comment]
Updated!
